<?php

/**
 * BaseFlower
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $type
 * @property string $name
 * @property string $description
 * @property integer $user_id
 * @property User $User
 * 
 * @method integer getType()        Returns the current record's "type" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method integer getUserId()      Returns the current record's "user_id" value
 * @method User    getUser()        Returns the current record's "User" value
 * @method Flower  setType()        Sets the current record's "type" value
 * @method Flower  setName()        Sets the current record's "name" value
 * @method Flower  setDescription() Sets the current record's "description" value
 * @method Flower  setUserId()      Sets the current record's "user_id" value
 * @method Flower  setUser()        Sets the current record's "User" value
 * 
 * @package    hamaspyur
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFlower extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('flower');
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}