<?php

/**
 * BasePetal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $flower1_id
 * @property integer $flower2_id
 * @property integer $connection_id
 * @property string $colour
 * 
 * @method integer getFlower1Id()     Returns the current record's "flower1_id" value
 * @method integer getFlower2Id()     Returns the current record's "flower2_id" value
 * @method integer getConnectionId()  Returns the current record's "connection_id" value
 * @method string  getColour()        Returns the current record's "colour" value
 * @method Petal   setFlower1Id()     Sets the current record's "flower1_id" value
 * @method Petal   setFlower2Id()     Sets the current record's "flower2_id" value
 * @method Petal   setConnectionId()  Sets the current record's "connection_id" value
 * @method Petal   setColour()        Sets the current record's "colour" value
 * 
 * @package    hamaspyur
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePetal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('petal');
        $this->hasColumn('flower1_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('flower2_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('connection_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('colour', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}