<?php

/**
 * Flower
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hamaspyur
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Flower extends BaseFlower
{
  public function getPetals()
  {
    return PetalTable::getFlowerPetals($this);
  }
}