<?php

/**
 * FlowerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlowerTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object FlowerTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Flower');
  }
}