<?php

/**
 * Petal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hamaspyur
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Petal extends BasePetal
{
  protected $flower;

  public function setFlower($flower)
  {
    $this->flower = $flower;
  }

  public function getFlower()
  {
    return $this->flower;
  }

  public function getConnection()
  {
    if ($this->getFlower()->getType() == sfConfig::get('petal_type_flower'))
    {
      return FlowerTable::getInstance()->find($this->getConnectionId());
    }
    elseif ($this->getFlower()->getType() == sfConfig::get('petal_type_user'))
    {
      return UserTable::getInstance()->find($this->getConnectionId());
    }
  }
}