<?php

/**
 * PetalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PetalTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PetalTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Petal');
  }

  public static function getFlowerPetals($flower)
  {
    $q = self::getInstance()->createQuery('q')
      ->where("q.flower1_id = " . $flower->getId());

    $petals = $q->execute();

    foreach($petals as $petal)
      $petal->setFlower($flower);

    return $petals;
  }
}